YML File

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -120,11 +120,18 @@ jobs:
     steps:
       - checkout
       - run:
-          name: Heroku Deploy
-          command: echo todo && false
+           name: Heroku Deploy
+           command: |
+             git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git main
       - run:
-          name: Smoke Test
-          command: echo todo && false
+           name: Smoke Test
+           command:  |
+             HTTPCODE=`curl -s -o /dev/null -w "%{http_code}" https://$HEROKU_APP_NAME.herokuapp.com/`
+             if [ "$HTTPCODE" -ne 200 ];then
+                 echo "heroku app not responding, failing deploy"
+                 exit 1
+             fi
+
 
 workflows:
   version: 2
